name: Build

permissions: {}

on:
  workflow_call:
    outputs:
      cache-key:
        value: ${{ jobs.build.outputs.cache-key }}

jobs:
  build:
    concurrency: build-${{ github.ref }}
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm clean-install
      - id: cache-key
        run: echo "value=dist-${{ hashFiles('src/**/*.ts', 'tsconfig.json', 'tsconfig/*.json', 'package.json', 'jsr.json', 'tools/*.cjs', 'tools/*.js', '.github/workflows/*.yml', 'package-lock.json') }}" >> $GITHUB_OUTPUT
      - name: Cache dist
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: dist
        with:
          path: dist
          key: ${{ steps.cache-key.outputs.value }}
      - name: Build
        run: npm run build-all
        if: ${{ steps.dist.outputs.cache-hit != 'true' }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist
          path: dist
      - run: git reset HEAD --hard
