name: Release

permissions: {}

on:
  push:
    tags: ['v6.[0-9]+.[0-9]+']

jobs:
  release:
    permissions:
      actions: read
      contents: write
      discussions: write
      id-token: write
    uses: panva/.github/.github/workflows/npm-release.yml@main
    with:
      cleanup_paths: '["dist"]'
      prepare_command: npm clean-install && npm run build-all && node tools/publish.cjs
      publish_jsr: true
