name: Test

permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '11 11 * * 1'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  node-versions:
    uses: panva/.github/.github/workflows/node-versions.yml@main
    with:
      min: 20

  node:
    needs:
      - node-versions
    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJSON(needs.node-versions.outputs.matrix) }}
        suite:
          - tap:node
          - test

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup node
        id: node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          check-latest: true
      - run: npm clean-install
      - name: Run Test Suite
        run: npm run ${{ matrix.suite }}

  deno:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: latest
      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm clean-install
      - name: Test Deno Definitions
        run: |
          npm run build:deno
          deno check dist/deno/index.ts
      - name: Test Deno
        run: npm run tap:deno

  bun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: latest
      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm clean-install
      - name: Test Bun
        run: npm run tap:bun

  workerd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm clean-install
      - run: npm install --global workerd
      - run: npm link workerd
      - name: Run Test Suite
        run: npm run tap:workerd

  browsers:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, safari]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm clean-install
      - run: npm upgrade playwright
      - name: get playwright version
        id: playwright-version
        run:
          echo "version=$(npm list playwright --json | jq -r '.dependencies["@playwright/test"].dependencies.playwright.version')" >>
          $GITHUB_OUTPUT
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/Library/Caches/ms-playwright
          key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}
      - run: npx playwright install --only-shell chromium firefox webkit
      - name: Run Test Suite
        run: npm run tap:browsers
        env:
          BROWSER: ${{ matrix.browser }}

  electron:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm clean-install
      - name: Install Electron
        run: npm install --global electron
      - name: Run Test Suite
        run: npm run tap:electron
